/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GuildsRouteImport } from './routes/guilds'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumThreadIdRouteImport } from './routes/forum.$threadId'
import { Route as PlayWorldMissionRouteImport } from './routes/play.$world.$mission'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsRoute = GuildsRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumThreadIdRoute = ForumThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ForumRoute,
} as any)
const PlayWorldMissionRoute = PlayWorldMissionRouteImport.update({
  id: '/play/$world/$mission',
  path: '/play/$world/$mission',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/forum': typeof ForumRouteWithChildren
  '/guilds': typeof GuildsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/play/$world/$mission': typeof PlayWorldMissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/forum': typeof ForumRouteWithChildren
  '/guilds': typeof GuildsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/play/$world/$mission': typeof PlayWorldMissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/forum': typeof ForumRouteWithChildren
  '/guilds': typeof GuildsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/play/$world/$mission': typeof PlayWorldMissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/battle'
    | '/forum'
    | '/guilds'
    | '/leaderboard'
    | '/profile'
    | '/quests'
    | '/sitemap.xml'
    | '/forum/$threadId'
    | '/play/$world/$mission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/battle'
    | '/forum'
    | '/guilds'
    | '/leaderboard'
    | '/profile'
    | '/quests'
    | '/sitemap.xml'
    | '/forum/$threadId'
    | '/play/$world/$mission'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/battle'
    | '/forum'
    | '/guilds'
    | '/leaderboard'
    | '/profile'
    | '/quests'
    | '/sitemap.xml'
    | '/forum/$threadId'
    | '/play/$world/$mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BattleRoute: typeof BattleRoute
  ForumRoute: typeof ForumRouteWithChildren
  GuildsRoute: typeof GuildsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  QuestsRoute: typeof QuestsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PlayWorldMissionRoute: typeof PlayWorldMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds': {
      id: '/guilds'
      path: '/guilds'
      fullPath: '/guilds'
      preLoaderRoute: typeof GuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$threadId': {
      id: '/forum/$threadId'
      path: '/$threadId'
      fullPath: '/forum/$threadId'
      preLoaderRoute: typeof ForumThreadIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/play/$world/$mission': {
      id: '/play/$world/$mission'
      path: '/play/$world/$mission'
      fullPath: '/play/$world/$mission'
      preLoaderRoute: typeof PlayWorldMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ForumRouteChildren {
  ForumThreadIdRoute: typeof ForumThreadIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumThreadIdRoute: ForumThreadIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BattleRoute: BattleRoute,
  ForumRoute: ForumRouteWithChildren,
  GuildsRoute: GuildsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  QuestsRoute: QuestsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PlayWorldMissionRoute: PlayWorldMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
